routers:
  - id: dev
    label: Dev
    type: routeros
    host_env: ROUTER_DEV_HOST
    port_env: ROUTER_DEV_PORT
    user_env: ROUTER_DEV_USER
    key_env: ROUTER_DEV_KEY

actions:
  - id: health
    label: Health
    description: Get resources print
    targets:
      - routeros
    run:
      - /system/identity/print
      - /system/resource/print

  - id: ips
    label: Ips
    description: Get interfaces and addresses
    targets:
      - routeros
    run:
      - /ip/address/print

  - id: routes
    label: Routes
    description: Get available routes
    targets:
      - routeros
    run:
      - /ip/route/print
